### ISSUE TITLE
✏️Shopify.HMAC.verify/3 in README should be Shopify.OAuth.verify_hmac/3

### ISSUE THREAD

**Issue by kurt-friedrich** [malomohq/shopify-oauth-elixir#3]
Example for `verify_hmac/3` uses nonexistent `Shopify.HMAC.verify/3` instead of `Shopify.OAuth.verify_hmac/3`:

https://github.com/malomohq/shopify-oauth-elixir/blob/master/README.md#verifying-hmac-signatures

**Comment by kurt-friedrich** [comment]
@anthonator I have a PR ready for this if you could please give me write access

**Comment by anthonator** [comment]
Go ahead and fork this repo and issue a pull request.
